#!/usr/bin/env bash
set -euo pipefail

# new_vertical.sh
# Create a new Vertical YAML config with sane defaults, including multi-source ingestion.
#
# Usage:
#   ./new_vertical.sh <vertical_id> [--title "Title"] [--description "Desc"] [--enabled true|false]
#                     [--priority 10] [--sources "reddit,hackernews,indiehackers,producthunt"]
#                     [--limit 80] [--out-dir "config/verticals"] [--overwrite]
#
# Examples:
#   ./new_vertical.sh testing --title "Testing" --sources "reddit,hackernews,indiehackers"
#   ./new_vertical.sh b2c_security_industry_ecommerce_support_ops --priority 30 --sources "reddit,producthunt" --limit 60

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

die() { echo "error: $*" >&2; exit 1; }

# ---- defaults (match your taxonomy intent) ----
OUT_DIR_DEFAULT="config/verticals"
ENABLED_DEFAULT="true"
PRIORITY_DEFAULT="10"
LIMIT_DEFAULT="80"
SOURCES_DEFAULT="reddit,hackernews,indiehackers"
LANG_ALLOWLIST_DEFAULT="en"
MIN_SIGNAL_QUALITY_DEFAULT="0.2"

vertical_id=""
title=""
description=""
enabled="$ENABLED_DEFAULT"
priority="$PRIORITY_DEFAULT"
sources_csv="$SOURCES_DEFAULT"
limit="$LIMIT_DEFAULT"
out_dir="$OUT_DIR_DEFAULT"
overwrite="false"

# ---- arg parsing ----
if [[ $# -lt 1 ]]; then
  die "Missing <vertical_id>. Run: ./new_vertical.sh <vertical_id> [--title ...]"
fi

vertical_id="$1"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --title) shift; title="${1:-}";;
    --description) shift; description="${1:-}";;
    --enabled) shift; enabled="${1:-}";;
    --priority) shift; priority="${1:-}";;
    --sources) shift; sources_csv="${1:-}";;
    --limit) shift; limit="${1:-}";;
    --out-dir) shift; out_dir="${1:-}";;
    --overwrite) overwrite="true";;
    -h|--help)
      sed -n '1,80p' "$0"
      exit 0
      ;;
    *) die "Unknown arg: $1";;
  esac
  shift
done

# ---- validation ----
[[ "$vertical_id" =~ ^[a-z0-9_]+$ ]] || die "vertical_id must match ^[a-z0-9_]+$ (got: $vertical_id)"
[[ "${#vertical_id}" -le 80 ]] || die "vertical_id too long (max 80)"
[[ "$enabled" == "true" || "$enabled" == "false" ]] || die "--enabled must be true|false"
[[ "$priority" =~ ^[0-9]+$ ]] || die "--priority must be an integer"
[[ "$limit" =~ ^[0-9]+$ ]] || die "--limit must be an integer"
(( limit > 0 )) || die "--limit must be > 0"

# defaults for title/description if not provided
if [[ -z "$title" ]]; then
  # human-ish default: replace _ with space, titlecase-ish (light)
  title="$(echo "$vertical_id" | tr '_' ' ')"
fi
if [[ -z "$description" ]]; then
  description="General pains and workflows around $title."
fi

# output path
mkdir -p "$REPO_ROOT/$out_dir"
out_file="$REPO_ROOT/$out_dir/${vertical_id}.yml"

if [[ -f "$out_file" && "$overwrite" != "true" ]]; then
  die "File already exists: $out_file (use --overwrite to replace)"
fi

# ---- build ingestion.sources YAML from CSV ----
# Normalize: split by comma, trim spaces, drop empties, stable lexicographic if you want determinism.
IFS=',' read -r -a sources_arr <<< "$sources_csv"

# trim + filter empties
clean_sources=()
for s in "${sources_arr[@]}"; do
  ss="$(echo "$s" | awk '{$1=$1};1')" # trim
  [[ -n "$ss" ]] && clean_sources+=("$ss")
done

(( ${#clean_sources[@]} > 0 )) || die "--sources resolved to empty list"

# Optional: stable order for determinism (lexicographic)
# Comment out if you prefer to preserve user order.
IFS=$'\n' clean_sources=($(printf "%s\n" "${clean_sources[@]}" | sort))
unset IFS

sources_yaml=""
for src in "${clean_sources[@]}"; do
  sources_yaml+="  - name: ${src}\n"
  sources_yaml+="    query: null\n"
  sources_yaml+="    limit: ${limit}\n"
done

# ---- write file ----
cat > "$out_file" <<YAML
# Generated by scripts/new_vertical.sh
id: ${vertical_id}
name: ${vertical_id}
title: "${title}"
description: "${description}"
version: 1
enabled: ${enabled}
priority: ${priority}

# Optional tags (free-form). Keep minimal; taxonomy engine can also generate tags.
tags:
  - "${vertical_id}"

# Default queries (minimum 3 recommended). Fill these for better signal quality.
default_queries:
  - "${title}"
  - "${title} pain"
  - "${title} bottleneck"

# Ingestion config (multi-source)
ingestion:
  # Per-vertical overrides; global defaults can still exist in taxonomy engine.
  language_allowlist:
    - "${LANG_ALLOWLIST_DEFAULT}"
  min_signal_quality: ${MIN_SIGNAL_QUALITY_DEFAULT}
  sources:
$(printf "%b" "$sources_yaml")
YAML

echo "OK: created $out_file"
echo "Next:"
echo "  - Edit default_queries (3–12 is a good range)"
echo "  - Run a smoke ingestion:"
echo "      SOURCE=$(printf "%s" "${clean_sources[0]}") QUERY=\"${title}\" LIMIT=${limit} bash scripts/run_scheduler_once.sh"
