from __future__ import annotations

from domain.models.persona import Persona

# Rule-based v1: lexicons / markers (expand iteratively)
# Keep markers short and high-precision; bias toward precision over recall.

PERSONA_MARKERS: dict[Persona, dict[str, list[str]]] = {
    Persona.founder: {
        "strong": [
            "mrr",
            "arr",
            "my saas",
            "our saas",
            "startup",
            "founder",
            "cofounder",
            "co-founder",
            "product-market fit",
            "pmf",
            "churn",
            "ltv",
            "cac",
            "runway",
            "investors",
            "seed round",
            "series a",
            "pricing page",
            "stripe",
        ],
        "weak": [
            "users",
            "activation",
            "retention",
            "onboarding",
            "b2b",
            "b2c",
            "gtm",
            "trial",
        ],
    },
    Persona.operator: {
        "strong": [
            "ops",
            "operations",
            "incident",
            "on-call",
            "oncall",
            "pager",
            "sla",
            "slo",
            "sre",
            "devops",
            "runbook",
            "postmortem",
            "etl",
            "pipeline",
            "deploy",
            "kubernetes",
            "k8s",
            "terraform",
            "monitoring",
            "observability",
        ],
        "weak": [
            "process",
            "workflow",
            "automation",
            "reliability",
            "maintenance",
        ],
    },
    Persona.freelancer: {
        "strong": [
            "client",
            "freelance",
            "freelancer",
            "contract",
            "invoice",
            "billing client",
            "scope creep",
            "proposal",
            "agency",
            "rate",
            "day rate",
            "deliverable",
        ],
        "weak": [
            "upwork",
            "fiverr",
            "retainer",
        ],
    },
    Persona.enterprise_employee: {
        "strong": [
            "my manager",
            "stakeholders",
            "enterprise",
            "procurement",
            "compliance",
            "security review",
            "legal review",
            "soc2",
            "iso 27001",
            "it department",
            "corporate",
            "jira",
            "confluence",
            "okr",
        ],
        "weak": [
            "approval",
            "policy",
            "internal tool",
        ],
    },
    Persona.hobbyist: {
        "strong": [
            "side project",
            "weekend project",
            "for fun",
            "learning",
            "i'm new",
            "beginner",
            "tutorial",
            "home lab",
            "homelab",
            "raspberry pi",
        ],
        "weak": [
            "experiment",
            "toy project",
        ],
    },
}
