ALTER TABLE cluster_daily_metrics
  ADD COLUMN IF NOT EXISTS score DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS velocity DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS source_count INTEGER;

ALTER TABLE cluster_daily_metrics
  ADD COLUMN IF NOT EXISTS score_volume DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS score_velocity DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS score_novelty DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS score_diversity DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS score_confidence DOUBLE PRECISION;
